export const styles = {
  TableHeaderStyledTabOne: {
    width: '10%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledTabTwo: {
    width: '20%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledTabThree: {
    width: '20%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledTabFour: {
    width: '20%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledTabFive: {
    width: '20%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    paddingRight: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#8c8c8c',
  },
  TableHeaderStyledButtons: {
    width: '10%',
    height: '22px',
    fontSize: '16px',
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '37px',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'left',
    color: '#8c8c8c',
  },
  TableHeaderHeight: {
    height: '50px',
  },
};