export const styles = {
  RowHeight: {
    height: '40px',
  },
  styleId: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '5%',
    paddingRight: '0px',
  },
  styleName: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '15%',
    paddingRight: '0px',
  },
  styleEmail: {
    paddingRight: '0px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '15%',
  },
  styleTitle: {
    paddingRight: '0px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
  },
  styleAbstract: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
    paddingRight: '0px',
  },
  styleBiography: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
    paddingRight: '0px',
  },
  ButtonCellStyle: {
    width: '5%',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'right',
    color: '#494949',
  },
};
