export const styles = {
  RowHeight: {
    height: '40px',
  },
  styleId: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '5%',
    paddingRight: '0px',
  },
  styleTheme: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
    paddingRight: '0px',
  },
  styleDate: {
    paddingRight: '0px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '10%',
  },
  styleSchedule: {
    paddingRight: '0px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '10%',
  },
  styleDirection: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
    paddingRight: '0px',
  },
  styleAttendance: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'center',
    color: '#494949',
    width: '10%',
    paddingRight: '0px',
    paddingLeft: '4%',
  },
  ButtonCellStyle: {
    width: '5%',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'right',
    color: '#494949',
  },
  switch: {
    backgroundColor: 'rgb(237, 28, 64)',
  },
  trackSwitched: {
    backgroundColor: '#ff9d9d',
  },
};
