export const styles = {
  InputLeftSide: {
    cursor: 'pointer',
    width: '42.5%',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    marginLeft: '25px',
    float: 'left',
  },
  InputRightSide: {
    cursor: 'pointer',
    width: '42.5%',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    float: 'right',
    marginRight: '25px',
  },
  InputLeftSideSpecial: {
    cursor: 'pointer',
    width: '90%',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    marginLeft: '25px',
    float: 'left',
  },
  InputRightSideSpecial: {
    cursor: 'pointer',
    width: '30%',
    overflow: 'visible',
    display: 'block',
    height: '40px',
    lineHeight: '0',
    padding: '2%',
    borderRadius: '4px',
    border: 'solid 1px #cac5c5',
    transition: 'all .25s',
    fontSize: '15px',
    float: 'right',
    marginRight: '25px',
  },
  textField: {
    marginTop: '0',
  },
};
