export const styles = {
  RowHeight: {
    height: '40px',
  },
  styleId: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '10%',
    paddingRight: '0px',
  },
  styleUsername: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
    paddingRight: '0px',
  },
  styleRol: {
    paddingRight: '0px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
  },
  styleUbicacion: {
    paddingRight: '0px',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
  },
  styleDate: {
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    paddingLeft: '0',
    textAlign: 'center',
    color: '#494949',
    width: '20%',
    paddingRight: '0px',
  },
  ButtonCellStyle: {
    width: '10%',
    height: '22px',
    fontSize: '16px',
    fontWeight: '500',
    fontStyle: 'normal',
    fontStretch: 'normal',
    paddingLeft: '0',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    textAlign: 'right',
    color: '#494949',
  },
};
